name: Quality Control
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install
          run: npm ci
        - name: Run lint
          shell: bash
          run: |
            if [[ $GITHUB_BASE_REF ]]
            then
              export NX_BASE=remotes/origin/$GITHUB_BASE_REF
            else
              export NX_BASE=$(git rev-parse HEAD~1)
            fi
            echo "Base => $NX_BASE"
            npm run format:check -- --base=$NX_BASE
            npm run affected:lint -- --base=$NX_BASE
