name: Quality Control
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Use Node.js
          uses: actions/setup-node@v1
        - name: Install
          run: npm ci
        - name: Run affectedLint
          run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run affectedTest
        shell: bash
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export NX_BASE=remotes/origin/$GITHUB_BASE_REF
          else
            export NX_BASE=$(git rev-parse HEAD~1)
          fi
          echo "Base => $NX_BASE"
          npm run format:check -- --base=$NX_BASE
          npm run affected:test -- --base=$NX_BASE
